# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  redis-master:
    image: docker.io/bitnami/redis-cluster:lastest
    container_name: redis_master
    ports:
      - 16379:6379/tcp
    volumes:
      - redis-cluster_data-0:/bitnami/redis/data
      - redis-master.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-master redis-slave-1 redis-slave-2'

  redis-slave-1:
    image: docker.io/bitnami/redis-cluster:lastest
    container_name: redis_slave_1
    ports:
      - 16380:6379/tcp
    depends_on:
      - redis_master
    volumes:
      - redis-slave-data-1:/bitnami/redis/data
      - redis-slave-1.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-master redis-slave-1 redis-slave-2'

  redis-slave-2:
    image: docker.io/bitnami/redis-cluster:lastest
    container_name: redis_slave_2
    ports:
      - 16381:6379/tcp
    depends_on:
      - redis_master
    volumes:
      - redis-slave-data-2:/bitnami/redis/data
      - redis-slave-2.conf:/opt/bitnami/redis/mounted-etc/redis.conf
    environment:
      - 'REDIS_PASSWORD=bitnami'
      - 'REDIS_NODES=redis-master redis-slave-1 redis-slave-2'

  # redis-node-3:
  #   image: docker.io/bitnami/redis-cluster:7.2
  #   volumes:
  #     - redis-cluster_data-3:/bitnami/redis/data
  #   environment:
  #     - 'REDIS_PASSWORD=bitnami'
  #     - 'REDIS_NODES=redis-master redis-slave-1 redis-slave-2 redis-node-3 redis-node-4 redis-node-5'

  # redis-node-4:
  #   image: docker.io/bitnami/redis-cluster:7.2
  #   volumes:
  #     - redis-cluster_data-4:/bitnami/redis/data
  #   environment:
  #     - 'REDIS_PASSWORD=bitnami'
  #     - 'REDIS_NODES=redis-master redis-slave-1 redis-slave-2 redis-node-3 redis-node-4 redis-node-5'

  # redis-node-5:
  #   image: docker.io/bitnami/redis-cluster:7.2
  #   volumes:
  #     - redis-cluster_data-5:/bitnami/redis/data
  #   depends_on:
  #     - redis-master
  #     - redis-slave-1
  #     - redis-slave-2
  #     - redis-node-3
  #     - redis-node-4
  #   environment:
  #     - 'REDIS_PASSWORD=bitnami'
  #     - 'REDISCLI_AUTH=bitnami'
  #     - 'REDIS_CLUSTER_REPLICAS=1'
  #     - 'REDIS_NODES=redis-master redis-slave-1 redis-slave-2 redis-node-3 redis-node-4 redis-node-5'
  #     - 'REDIS_CLUSTER_CREATOR=yes'

volumes:
  redis-master_data:
    driver: local
  redis-slave-data-1:
    driver: local
  redis-slave_data-2:
    driver: local
  # redis-cluster_data-3:
  #   driver: local
  # redis-cluster_data-4:
  #   driver: local
  # redis-cluster_data-5:
  #   driver: local
