# version: '3.7'
# services:
#   redis-master:
#     image: redis:latest
#     hostname: redis-slave-1
#     container_name: redis_slave_1
#     volumes:
#       - ./redis_slave_1:/data
#       - redis-slave-1.conf:/usr/local/etc/redis/redis.conf
#     ports:
#       - '16380:6379'

version: '3'
services:
  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    ports:
      - '6379:6379'
    command: redis-server --port 6380 --slaveof 10.0.0.243 6379
    networks:
      - redis-net
    volumes:
      - redis-slave1-data:/data
      - /redis-slave1/redis-slave-1.conf:/usr/local/etc/redis/redis.conf

  redis-sentinel:
    image: redis:latest
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    networks:
      - redis-net
    volumes:
      - /redis-sentinel:/etc/redis
    depends_on:
      - redis-slave1

networks:
  redis-net:
    driver: bridge

volumes:
  redis-slave1-data: