version: '3.7'
services:
  redis-master:
    image: redis:latest
    hostname: redis-master
    container_name: redis_master
    volumes:
      - redis_master:/data
      - ./redis-master.conf:/etc/redis/redis.conf
    ports:
      - '6379:6379'