version: '3.7'
services:
  redis-master:
    image: redis:latest
    hostname: redis-master
    container_name: redis_master
    volumes:
      - ./redis_master:/data
      - redis-master.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '16379:6379'
    command: redis-server

volumes:
  redis-master:
    driver: local
  