version: '3'
services:
  redis-master:
    image: redis:latest
    hostname: redis-master
    container_name: redis_master
    volumes:
      - redis-master:/data
      - redis-master/redis-master.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    command: redis-server

volumes:
  redis-master:
  